# Generated by Django 3.1.6 on 2021-03-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210325_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_company', models.CharField(default='', max_length=30)),
                ('driver', models.CharField(max_length=30)),
                ('driver_points', models.IntegerField(default=0)),
                ('price_scalar', models.FloatField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='catalog_items_per_page',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='catalog_last_search',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='catalog_sort_on',
            field=models.CharField(default='name', max_length=7),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='catalog_sort_order',
            field=models.CharField(default='up', max_length=4),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='list_items_per_page',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='list_last_search',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='list_sort_on',
            field=models.CharField(default='created', max_length=7),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='list_sort_order',
            field=models.CharField(default='up', max_length=4),
        ),
    ]
