# Generated by Django 3.1.6 on 2021-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210329_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='list_last_search',
            field=models.CharField(default='candle', max_length=50),
        ),
    ]
